#!/usr/bin/env python3
"""Build the distributable tileset from manifest.json + source-tiles/.

Outputs into dist/<directory>/:
  - the 32x32 atlas PNG (tiles composited at their manifest grid positions)
  - the graf-*.prf mapping file
  - a buildsys Makefile so FAangband's `make install` deploys the tileset
plus dist/list-stanza.txt, the lib/tiles/list.txt entry with @SERIAL@ left
for install.sh to fill in.

Source tiles may be any size; they are downscaled to tile_size. A tile with
"chroma": true has near-magenta (255,0,255) pixels keyed to transparent —
use this for AI-generated renders, which can't emit an alpha channel.
"""
import json
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CHROMA = (255, 0, 255)
CHROMA_TOL = 60


def key_out_chroma(img):
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if (abs(r - CHROMA[0]) < CHROMA_TOL
                    and abs(g - CHROMA[1]) < CHROMA_TOL
                    and abs(b - CHROMA[2]) < CHROMA_TOL):
                px[x, y] = (r, g, b, 0)
    return img


def main():
    m = json.loads((ROOT / "manifest.json").read_text())
    ts = m["tileset"]["tile_size"]
    tiles = m["tiles"]

    rows = max(t["row"] for t in tiles) + 1
    cols = max(t["col"] for t in tiles) + 1
    atlas = Image.new("RGBA", (cols * ts, rows * ts), (0, 0, 0, 0))

    seen = set()
    for t in tiles:
        pos = (t["row"], t["col"])
        if pos in seen:
            sys.exit(f"manifest error: duplicate grid cell {pos}")
        seen.add(pos)
        if t["row"] > 0x7F or t["col"] > 0x7F:
            sys.exit(f"manifest error: cell {pos} beyond the 128x128 prf limit")
        src = ROOT / "source-tiles" / t["source"]
        if not src.is_file():
            sys.exit(f"missing source tile: {src}")
        img = Image.open(src)
        if t.get("chroma"):
            img = key_out_chroma(img)
        img = img.convert("RGBA").resize((ts, ts), Image.LANCZOS)
        atlas.paste(img, (t["col"] * ts, t["row"] * ts))

    outdir = ROOT / "dist" / m["tileset"]["directory"]
    outdir.mkdir(parents=True, exist_ok=True)
    atlas.save(outdir / m["tileset"]["atlas"])

    prf = [
        f"# File: {m['tileset']['pref']}",
        "#",
        "# Generated by tools/build.py from manifest.json -- do not hand-edit.",
        "",
    ]
    for t in tiles:
        attr = 0x80 + t["row"]
        char = 0x80 + t["col"]
        for entity in t["maps"]:
            prf.append(f"{entity}:0x{attr:02X}:0x{char:02X}")
    (outdir / m["tileset"]["pref"]).write_text("\n".join(prf) + "\n")

    (outdir / "Makefile").write_text(
        "MKPATH=../../../mk/\n"
        "include $(MKPATH)buildsys.mk\n"
        "\n"
        f"DATA = {m['tileset']['atlas']} {m['tileset']['pref']}\n"
        "\n"
        f"PACKAGE = tiles/{m['tileset']['directory']}\n"
    )

    alpha = 1 if m["tileset"].get("alpha") else 0
    (ROOT / "dist" / "list-stanza.txt").write_text(
        f"name:@SERIAL@:{m['tileset']['name']}\n"
        f"directory:{m['tileset']['directory']}\n"
        f"size:{ts}:{ts}:{m['tileset']['atlas']}\n"
        f"pref:{m['tileset']['pref']}\n"
        f"extra:{alpha}:0:0\n"
    )

    mapped = sum(len(t["maps"]) for t in tiles)
    print(f"built {len(tiles)} tiles ({rows}x{cols} atlas), {mapped} prf mappings -> {outdir}")


if __name__ == "__main__":
    main()
