#!/usr/bin/env python3
"""Build the pinned LIGHT-mode atlas from the dark one (issue #13 D9).

Light mode ships as a runtime toggle with the two palettes PINNED, so the SAME
tileset serves both and no sprite is ever redrawn by hand (ledger
DEC-2026-07-23-pinned-light-dark-toggle).  This tool is the build half of that:

  1. Read the locked dark palette (palette.json).
  2. Compute the light palette as a LOCKED luminance transform of it -- hue and
     saturation preserved, lightness inverted (L' = 1 - L in HLS).  Because the
     light palette is a pure function of the dark one, the two can never drift.
  3. Remap the already-snapped dark atlas cell-for-cell: dark_palette[i] ->
     light_palette[i].  The dark atlas is exactly the 21 locked colours (the
     build snap forced that), so this remap is exact and lossless -- identical
     to re-snapping the source art to the light palette, but pinned by
     construction.
  4. Emit dist/<dir>-light/<atlas> plus palettes/{dark,light}.json for
     inspection, and the light `dark_colour` (the void/panel tone) the runtime
     color-table flip will use.

The runtime keybinding + texture swap is the companion C patch
(display-lightmode-*); this tool proves and produces the pinned art.
"""

import colorsys
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import build as B  # noqa: E402  reuse load_palette + ROOT


def light_of(rgb):
    """Locked luminance transform: keep hue+saturation, invert lightness."""
    r, g, b = (c / 255.0 for c in rgb)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    l2 = 1.0 - l
    r2, g2, b2 = colorsys.hls_to_rgb(h, l2, s)
    return tuple(round(c * 255) for c in (r2, g2, b2))


def _hex(rgb):
    return "#%02x%02x%02x" % rgb


def build_light_atlas(m):
    from PIL import Image

    dark_cols = B.load_palette()
    if not dark_cols:
        print("light: no palette.json -- cannot build a pinned light variant")
        return
    light_cols = [light_of(c) for c in dark_cols]

    # persist both palettes so the pinned relationship is inspectable
    pal_dir = B.ROOT / "palettes"
    pal_dir.mkdir(exist_ok=True)
    dark_src = json.loads((B.ROOT / "palette.json").read_text())
    (pal_dir / "dark.json").write_text(
        json.dumps(dark_src, indent=2) + "\n")
    (pal_dir / "light.json").write_text(json.dumps({
        "name": "Hither Lands (light)",
        "_comment": ("GENERATED by tools/build_light_atlas.py as a locked "
                     "luminance transform (L' = 1 - L, hue/sat kept) of "
                     "palette.json. Do not hand-edit; edit palette.json and "
                     "regenerate so the two stay pinned."),
        "colors": [_hex(c) for c in light_cols],
    }, indent=2) + "\n")

    ts = m["tileset"]
    dark_atlas = B.ROOT / "dist" / ts["directory"] / ts["atlas"]
    if not dark_atlas.exists():
        print(f"light: dark atlas {dark_atlas} missing -- run the tile build "
              "first; skipping")
        return
    img = Image.open(dark_atlas).convert("RGBA")

    remap = {c: light_cols[i] for i, c in enumerate(dark_cols)}
    px = img.load()
    W, H = img.size
    unmapped = 0
    for y in range(H):
        for x in range(W):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            key = (r, g, b)
            new = remap.get(key)
            if new is None:
                unmapped += 1
                continue
            px[x, y] = (new[0], new[1], new[2], a)

    out_dir = B.ROOT / "dist" / (ts["directory"] + "-light")
    out_dir.mkdir(parents=True, exist_ok=True)
    img.save(out_dir / ts["atlas"])

    # light void/panel tone: the dark_colour flipped the same way
    dark_void = ts.get("dark_colour", "#171310")
    light_void = _hex(light_of(tuple(
        int(dark_void.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))))
    (out_dir / "light_colour.txt").write_text(light_void + "\n")

    print(f"light: {out_dir.relative_to(B.ROOT)}/{ts['atlas']} "
          f"({W}x{H}, {len(dark_cols)} colours remapped, "
          f"{unmapped} px off-palette), void {dark_void} -> {light_void}")
    return {"dark": dark_cols, "light": light_cols,
            "void": (dark_void, light_void), "unmapped": unmapped}


if __name__ == "__main__":
    manifest = json.loads((B.ROOT / "manifest.json").read_text())
    build_light_atlas(manifest)
